### ISSUE TITLE
Simple HTML not converted from SMF 2.0.x

### ISSUE THREAD

**Issue by Frenzie** [OpenImporter/openimporter#103]
In SMF, simple HTML was stored like:

```
&lt;img src="whatever"&gt;
```

In Elk, that has become:

```
&lt;img src=&quot;whatever&quot;&gt;
```

This should preferably be converted during the import process.

**Comment by emanuele45** [comment]
I guess some overzealousness in htmlspecialchar'ring the body of the messages. :angel:

**Comment by Vekseid** [comment]
This is the wrong way around from what is occurring.

The converter changes

    &lt;img src=&quot;whatever&quot;&gt;

into 

    &lt;img src="whatever"&gt;

And Elkarte doesn't understand the result.

However, at least as of 1.1 " still gets converted into &quot; for the database, and ' to &#039;. It's still generating 

    <br />

On newlines.

The fixTexts method in the SMF common source is accordingly unnecessary and should be removed. It should only be a thing if/when Elkarte's handling of these things actually changes.

Even then, this should not be done on a row-by-row basis, but rather with a query that alters the database en masse, which is very quick and runs in seconds even for multi-million row conversions.
