### ISSUE TITLE
Typo in vbulletin4_importer.xml (line 56) leads to error "Unknown data type: 'id_cat'" during import

### ISSUE THREAD

**Issue by TheOneWhoseUsernameWasTaken** [OpenImporter/openimporter#113]
I'm trying to import a vb4 forum to Elkarte 1.0 (since there seems to be no 1.1 option, I'm using 1.0 as an intermediary step). The system is Debian 11 Bullseye (PHP 7.4, MariaDB 10.5).

I get this error:

```
Unsuccessful!
This query:

    ALTER TABLE `elkarte`.elkarte_categories
    CHANGE COLUM id_cat id_cat SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
    CHANGE COLUMN cat_order cat_order SMALLINT(5) NOT NULL;;

Caused the error:

    Unknown data type: 'id_cat'
```

I think this is due to a syntax error in line 56 of Importers/elkarte1.0/vbulletin4_importer.xml where it says "COLUM" instead of "COLUMN". The missing N causes the database to think "COLUM" is the column name, shifting all parameters by one.

It was easy enough to fix (process continued and is still running atm), just thought I'd report it.

**Comment by Spuds** [comment]
Thank you for the report!
