### ISSUE TITLE
Looking forward

### ISSUE THREAD

**Issue by emanuele45** [OpenImporter/openimporter#38]
I think I'm getting the grasp of what it has to be done to further separate the systems.
Do note: I'm thinking while writing, I will very likely change my mind while thinking and that will result in some inconsistency. Feel free to let me note it so to fix it. ;D

  1. Identify each step. I think an ```<step id="123">``` should be enough, that way we always know where we are at each step. The alternative (that is probably better) it's to use a name, for example ```<step id="member">``` that way it would be easier to create naming conventions to create methods to run at defined steps.
  2. Once identified, we can "trigger" before and after each step a specific method and transfer to that method all the ```<presql>``` stuff.
  3. Some of the tags are doing some random things, for example:
    * ```<detect>``` should be limited (if it is not yet) to "source" tables
    * ```<destination>``` obviously should be out to the destination code
    * ```<presql>``` contains mostly "destination-related" code (usually TRUNCATE of the target tables), so it should be fine;
    * ```<preparsecode>``` we should take a decision, I would "assign" it to the source (as far as I have seen, it's used mainly to fix potential errors in the data originated by the query, so should be the best option);
    * ```<presqlMethod>``` is a bit messed up because it is used to do many things (for example move the attachments, but in certain cases also ```<preparsecode>``` is used to move attachments... meh), what I would do is to split all these usages in two, separating the source from the destination and assign them to the ```<presql>``` and ```<preparsecode>``` accordingly;
    * ```<options>``` this is tricky again, because it may refer to both source and destination, I think. First off it is necessary to define if we actually need it when the transition is completed (I feel it may not be necessary in most of the cases, for example *no_add* should be useless, *ignore*... I'm not sure, *limit* should again be possible to ignore it).
the rest of the tags should be fine as they are now.
  4. Files: of course the directory structure should change *again*, at the moment is sub-divided reflecting the destination systems (elkarte1.0, wedge0.1, etc.), we'd need instead a "sources" and a "destinations" directories at least. That may result also in changes to the class names, but that's just a side  effect.

This is a brief summary of what I think there is to do from a slightly more technical point of view compared to #2.

Opinions are very welcome as usual.

**Comment by margarett** [comment]
Hi. I hope I'm not too late for the party here :tongue: 
Been trying to post here for quite some time but something always got in the way...

First things first, kudos for your work in openimporter.

I see that you already did much, much more but anyway I'd like to leave my thoughts on this. I've been trying to think about this (as I definitely want to move from the current SMF converters schema) but never got to any conclusion. Lack of coding skills mostly :tongue: 

With the current implementation of openimporter (and even with your current progress with the "intermediate array") you still need to have an "exporter" and an "importer" for each system. This, IMO, creates duplicate work.
The way I thought about it, you should only need 1 file per system, which would describe each section of the conversion, what the system offers or expects, etc. OI should then be able to compare each section of the "source" and "target" systems, skip (or use default values - if provided) to fields not matched, etc.

Something like this (excuse me for using XF and SMF as references, but I built a converter for it so it's more comfortable to me):
File 1: XF definitions file
```// ******* SCRIPT DATA FOR XenForo 1.2 ********** //
$script_data = array(
			'target_software' => 'XenForo',
			'target_version' => '1.2',
			'test_table' => 'user', //Test table for the connection test
		);
	
$data = array(
			'members' = array(
					'presql' = 'TRUNCATE ' . {$prefix} . 'user',
					'id' = array(
							'table_name' = {$prefix} . 'user',
							'column' = 'user_id',
							'type' = 'mediumint',
					),
					'username' = array(
							'table_name' = {$prefix} . 'user',
							'column' = 'username',
							'type' = 'string',
					),
					'date_register' = array(
							'table_name' = {$prefix} . 'user',
							'column' = 'register_date',
							'type' = 'unix_date',
							'default' = 0,
					),
			),
			'categories' = array(
			
			
			),
);```
File 2: SMF definitions file
```// ******* SCRIPT DATA FOR SMF 2.0.x ********** //
$script_data = array(
			'target_software' => 'SMF',
			'target_version' => '2.0.x',
			'test_table' => 'members', //Test table for the connection test
		);
	
$data = array(
			'members' = array(
					'presql' = 'TRUNCATE ' . {$prefix} . 'members',
					'id' = array(
							'table_name' = {$prefix} . 'members',
							'column' = 'id_member',
							'type' = 'mediumint',
					),
					'username' = array(
							'table_name' = {$prefix} . 'members',
							'column' = 'member_name',
							'type' = 'string',
					),
					'date_register' = array(
							'table_name' = {$prefix} . 'members',
							'column' = 'date_registered',
							'type' = 'unix_date',
							'default' = 0,
					),
			),
			'categories' = array(
			
			
			),
);```
Of course this is *extremely* incomplete and the first semi-working version of it would represent a severe workload. But it's just to show the principle.
The main goal would be to have just a single file for each system, dynamically built queries (instead of the current fixed ones) and automatically converted field types (to try to kill the annoying "wrong value sent to the database" errors)

**Comment by margarett** [comment]
Eh, sorry, the code got all messed up :(

**Comment by emanuele45** [comment]
>Hi. I hope I'm not too late for the party here :tongue:

Don't worry, it's never too late, things can change! :stuck_out_tongue: 

>Been trying to post here for quite some time but something always got in the way...

I know the feeling. :angel: 

> Lack of coding skills mostly :tongue: 

Well, we are on the same boat here. :lollipop: 

>I see that you already did much, much more but anyway I'd like to leave my thoughts on this. I've been trying to think about this (as I definitely want to move from the current SMF converters schema) but never got to any conclusion.

Thanks for taking the time to share your ideas! :grinning: 

If I got it right, I think this won't work the way you think it would. It's an approach I explored (at least in my mind). Of course it's very nice and dandy, but it has one big problem: you cannot generalize all the steps in a way flexible enough to accommodate such solution without a quite big amount of complexity.
For example I have in mind already three examples that would require three different approaches:
  1. messenger fields in SMF 2.0 and custom fields in other systems,
  2. https://github.com/emanuele45/openimporter/blob/abstraction/importer/Importers/sources/wbb3_importer.php#L89
  3. polls in vB4

In all these cases you already need (at least) two different *functions*: one to import, one to export. There is no way to obtain the result with just a "description" of the data structure, you have to manipulate the result of the query to and from the system.

At the moment, my idea of reduce code duplication is abstract classes. Any code shared by more than one importer/exporter can be pushed to an abstract class and shared.

Anyway, this is of course just my thoughts, and I may be badly wrong... it wouldn't be anything new. :angel: 

> Of course this is extremely incomplete and the first semi-working version of it would represent a severe workload. But it's just to show the principle.

Honestly I'm not really concerned by performance at the moment (and likely in the future): this is not something used every day, so the main goal is to have things done, time is not a constrain (if it takes 1 hour or 1 hour and 10 minutes nobody would complain).

> The main goal would be to have just a single file for each system, dynamically built queries (instead of the current fixed ones) and automatically converted field types (to try to kill the annoying "wrong value sent to the database" errors)

That will be taken into account by the system I'm building in two steps (again):
  1. importer_skeleton.yml will (at some point) hold the expected data types (and/or values if needed)
  2. the "destination" system, if necessary, will take care of converting data not properly formatted (and it will know what data are not properly formatted by knowing the expected data-type from importer_skeleton.yml).


And don't be discouraged by what I wrote, as I said before things can change and I may be wrong. ;D

**Comment by margarett** [comment]
I'm still not convinced :tongue:  (although I can't argue with the time and effort you already put into this)

Those functions (that I understand are needed, of course - SMF converters also have PHP being executed to "adapt" content) can also be defined in that structure. So you can have not just the description of the data structure but also some function description that, if existent, can be executed.
I represented this in a PHP array, but any other way of defining it is perfectly valid.
Abstract classes seems a great idea, though ;-) I like the idea of reduce shared code :-)

**Comment by emanuele45** [comment]
I feel all the points in the original issue has been taken care of, so I'm closing this.
Of course it's open for discussion and other issues can be created.
