### ISSUE TITLE
Unknown column 'icons'

### ISSUE THREAD

**Issue by interlab** [OpenImporter/openimporter#61]
fixed

**Comment by interlab** [comment]
Unsuccessful!
This query:

    TRUNCATE `smf208`.smf_custom_fields_data;;

Caused the error:

    Table 'smf208.smf_custom_fields_data' doesn't exist

Line: 108
File: C:\apache\php\localhost\www\smf208\importer\OpenImporter\Database.php

**Comment by interlab** [comment]
Unsuccessful!
This query:

    SELECT mem.id_member, COUNT(pmr.id_pm) AS real_num, mem.personal_messages
    FROM `smf208`.smf_members AS mem
    LEFT JOIN `smf208`.smf_pm_recipients AS pmr ON (mem.id_member = pmr.id_member AND pmr.deleted = 0)
    GROUP BY mem.id_member
    HAVING real_num != personal_messages;

Caused the error:

    Unknown column 'mem.personal_messages' in 'field list'

Line: 108
File: C:\apache\php\localhost\www\smf208\importer\OpenImporter\Database.php

**Comment by interlab** [comment]
Recalculating statistics...
Unsuccessful!
This query:

    SELECT COUNT(*) AS count, t.id_topic
    FROM `smf208`.smf_message_likes AS ml
    INNER JOIN `smf208`.smf_topics AS t ON (t.id_first_msg = ml.id_msg)
    GROUP BY t.id_topic;

Caused the error:

    Table 'smf208.smf_message_likes' doesn't exist

Line: 108
File: C:\apache\php\localhost\www\smf208\importer\OpenImporter\Database.php

**Comment by emanuele45** [comment]
Whatever happened hope it was not a bug.
