### ISSUE TITLE
Autoload DBAL seems not to work

### ISSUE THREAD

**Issue by margarett** [OpenImporter/openimporter#70]
This is clearly me not knowing what I am doing :tongue: 

I get this error when entering Step1
Fatal error: Class 'OpenImporter\Core\Configuration' not found in C:\xampp\htdocs\importer\OpenImporter\ImporterSetup.php on line 255

Digging a little bit and using print_r(get_declared_classes()); I see that there is nothing DBAL-related loaded.

Any idea?

**Comment by emanuele45** [comment]
That's just me being dumb moving stuff around and forgetting to use ```use```...

Add:
```
use Doctrine\DBAL\Configuration;
use Doctrine\DBAL\DriverManager;
```
after the namespace declaration and should work.

**Comment by margarett** [comment]
It does, thanks ;)
