### ISSUE TITLE
Development branch - avatars with extra \'

### ISSUE THREAD

**Issue by margarett** [OpenImporter/openimporter#71]
Hi

I'm lurking around with MyBB's importer (as I want to create a new one for 1.8 but first want to try this out - while learning OI) and I stumbled on something: avatars:
Uploaded avatars are copied but not displayed. Looking at the database they look like this
filename: \'avatar_2.jpg\'
file_hash: \'832c8a8b4445e22c6d77663cd680f3b403e419

Looking at the code (uffff :tongue: ) I found this in SmfCommonOriginStep1.php

```php
				'filename' => '\'' . $row['filename'] . '\'',
				'file_hash' => '\'' . $file_hash . '\'',
```

Why these extra characters?

**Comment by emanuele45** [comment]
By the look of them, it seems just a remnant of refactoring (i.e. I changed it and forgot to remove it) that are then escaped by the DBAL leading to the result you see in the database.
I feel they can be removed.
