### ISSUE TITLE
Error in OpenImporter?

### ISSUE THREAD

**Issue by KeiroD** [OpenImporter/openimporter#94]
Looks like you guys have an error, see:

```
Trying to get property of non-object
/home/lysharia/public_html/importer/OpenImporter/Importer.php
470
```

I was trying to import SMF and SimplePortal. Maybe I should uninstall SimplePortal...

Nothing was shown other than that... even if I refresh.

Edit: And going back to http://lysharia.com/importer causes this to happen:

```
Unable to find the settings for SMF 2.0. Please double check the path and try again.
error_line 347
error_file /home/lysharia/public_html/importer/OpenImporter/Importer.php
```

O_o

**Comment by KeiroD** [comment]
Well, I was able to eventually resolve the issue and port my forum over to Elkarte... it's up and running @ https://lysharia.com so I'm not sure if this matters... so I suppose I'll close it for now.

Makes it easier to reference in the future if I encounter the same issue, though.

**Comment by emanuele45** [comment]
Sorry for overlooking this one... :blush: 
I'm pretty sure it is a bug, so let's keep it open. ;)
Did you use the "master" or the "development" branch?

**Comment by KeiroD** [comment]
Was 1.0.5 but I can try either if you'd like. I don't think I have an SMF database lying about however, I think... but it's trivial enough for me to reproduce. I'll do that after I do an import of a phpbb3 forum...
