### ISSUE TITLE
You must select a step

### ISSUE THREAD

**Issue by KeiroD** [OpenImporter/openimporter#96]
Forum importing from: PHPBB3 3.0.14
Forum importing to: Elkarte 1.0.5

Error produced:

```
You must select at least one step to import.
error_line 297
error_file /home/poir/web/poir.heimkoma.com/public_html/test/importer/OpenImporter/Importer.php
```

Steps:

Install Elkarte, upload openimporter to server. Select Elkarte 1.0, select phpbb3, it instantly creates the error.

Tried `rm -rf importer` but that isn't working.

**Comment by wintstar** [comment]
http://www.elkarte.net/community/index.php?topic=2862.0

**Comment by KeiroD** [comment]
Ah.

However, while I did install composer.phar... I see that PHPBB3 is now no longer showing as an available source to port over from. Is PHPBoost3 the option I should use when porting from PHPBB3?

**Comment by KeiroD** [comment]
Ah, I see that the issue is already present: #90 which is what I'm having now. :P

**Comment by Spuds** [comment]
same issue as #109 and fixed there
